apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: shop-service
  # --- CORRECTION HERE ---
  namespace: '978458840399' # Use Project NUMBER, not ID
  annotations:
    run.googleapis.com/launch-stage: BETA
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "1"
        autoscaling.knative.dev/maxScale: "10"
        # Optional: run.googleapis.com/container-dependencies: "{backend: [frontend]}"
    spec:
      containers:
        # --- Frontend (ingress) ---
        - name: frontend
          image: gcr.io/kalakaari-ai/shop-frontend:latest # Ensure this path is correct
          ports:
            - name: http1
              containerPort: 8080 # Nginx listens on $PORT (usually 8080)
          resources:
            limits:
              cpu: 1000m
              memory: 512Mi
        # --- Backend (sidecar) ---
        - name: backend
          image: gcr.io/kalakaari-ai/shop-backend:latest # Ensure this path is correct
          env:
            - name: PORT
              value: "8000"
            - name: MONGO_URI
              value: "mongodb+srv://shashank28:shash2811@shashank28.ytqocxe.mongodb.net/?retryWrites=true&w=majority&appName=shashank28"
            - name: DB_NAME
              value: "kalaakari_shop_db"
            - name: SECRET_KEY
              value: "shashankpatil2811"
          # Using startupProbe instead of HEALTHCHECK in Dockerfile for Cloud Run
          startupProbe:
            httpGet:
              path: / # Check root path of backend
              port: 8000 # On the internal port
            periodSeconds: 5
            failureThreshold: 24 # ~2 minutes total timeout (24 * 5s)
            timeoutSeconds: 4
          resources:
            limits:
              cpu: 1000m
              memory: 512Mi